name: slacky
version: 0.1.0.0

ghc-options: -Wall

dependencies:
  - base

default-extensions:
  - OverloadedStrings

library:
  source-dirs: src
  dependencies:
    - bytestring
    - text
    - wreq

executables:
  slacky:
    source-dirs: app
    main: Main.hs
    ghc-options: -threaded
    dependencies:
      - slacky
