name: slacky
version: 0.1.0.0

ghc-options: -Wall

default-extensions:
  - LambdaCase
  - OverloadedStrings
  - NoImplicitPrelude
  - RecordWildCards

dependencies:
  - base
  - containers
  - text
  - unix

library:
  source-dirs: src
  exposed-modules:
    - Slack.API.RTM.Start
    - Slacky.Client
    - Slacky.Globals
    - Slacky.Lockf
    - Slacky.Logger
    - Slacky.Prelude
    - Slacky.Server
  dependencies:
    - aeson
    - bytestring
    - http-types
    - microlens
    - network
    - network-uri
    - safe-exceptions
    - slack-api
    - text-format
    - wai
    - warp
    - wreq

executables:
  slacky:
    source-dirs: app
    main: Main.hs
    ghc-options: -threaded
    dependencies:
      - async
      - directory
      - slacky
      - stm
      - websockets
      - wuss
