name: slacky
version: 0.1.0.0

ghc-options: -Wall

dependencies:
  - aeson
  - base
  - text-format

default-extensions:
  - InstanceSigs
  - LambdaCase
  - OverloadedStrings
  - RecordWildCards
  - ViewPatterns

library:
  source-dirs: src
  dependencies:
    - bytestring
    - network-uri
    - text
    - transformers
    - vector
    - wreq

executables:
  slacky:
    source-dirs: app
    main: Main.hs
    ghc-options: -threaded
    dependencies:
      - slacky
      - wreq

tests:
  spec:
    source-dirs: test
    main: Spec.hs
    default-extensions:
      - OverloadedLists
      - QuasiQuotes
    dependencies:
      - aeson-qq
      - hspec
      - slacky
