name: slacky
version: 0.1.0.0

ghc-options: -Wall

default-extensions:
  - DeriveFunctor
  - FlexibleContexts
  - FlexibleInstances
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NoImplicitPrelude
  - OverloadedStrings
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - TypeFamilies
  - ViewPatterns

dependencies:
  - aeson
  - base
  - containers
  - monad-unlift
  - text
  - unix

library:
  source-dirs: src
  exposed-modules:
    - Slack.API.RTM.Start
    - Slacky.Async
    - Slacky.Client
    - Slacky.Globals
    - Slacky.Lockf
    - Slacky.LoggerT
    - Slacky.Prelude
    - Slacky.Server
  dependencies:
    - async
    - bytestring
    - http-types
    - microlens
    - monad-control
    - mtl
    - network
    - network-uri
    - safe-exceptions
    - slack-api
    - text-format
    - transformers
    - transformers-base
    - wai
    - warp
    - wreq

executables:
  slacky:
    source-dirs: app
    main: Main.hs
    ghc-options: -threaded
    dependencies:
      - directory
      - slacky
      - stm
      - websockets
      - wuss
